const endPoints = {
  // for admin
  auth: {
    login: "/login",
    register: "/register",
    logout: "/logout",
    permissions: "/permissions/:id",
    getMe: "/me",
    getAdmins: "/admins",
    updatePermissions: "/admins/:id/permissions",
    updateStatus: "/admins/:id/status",
    listAdmins: "/admin-management",
    createAdmin: "/admin-management",
    updateAdmin: "/admin-management/:id",
    updateAdminStatus: "/admin-management/:id/status",
    adminManagementupdatePermissions: "/admin-management/:id/permissions",
  },
  car: {
    upsertCar: "/upsert",
    getAllCars: "/",
    getCarsForList: "/list",
    getCarById: "/:id",
    deleteCarById: "/:id",
    toggleCarStatus: "/:id/status",
    getCarsBySubPackageId: "/by-sub-package/:sub_package_id",
  },
  dashboard: {
    getDashboardStats: "/stats",
    getRecentActivity: "/recent-activity",
    getPendingApprovals: "/pending-approvals",
    getOnlineDrivers: "/online-drivers",
  },
  driver: {
    getAllDrivers: "/",
    getDriverById: "/:id",
    approveDriver: "/:id/approve",
    rejectDriver: "/:id/reject",
    blockDriver: "/:id/block",
    unblockDriver: "/:id/unblock",
    verifyLicense: "/:id/verify-license",
    rejectLicense: "/:id/reject-license",
    verifyEmirates: "/:id/verify-emirates",
    rejectEmirates: "/:id/reject-emirates",
  },
  driverreports: {
    all: "/all",
    exportAll: "/export-all",
    exportDriver: "/export/:driverId",
    getDriverById: "/:driverId",
  },
  earning: {
    earningsHistory: "/get-all-earnings-history",
    singleDownload: "/single-download/:id",
    downloadAll: "/download-all",
  },
  notifications: {
    sent: "/sent",
    all: "/all",
    view: "/view/:id",
    delete: "/delete/:id",
  },
  package: {
    upsertPackage: "/upsert",
    getAllPackages: "/",
    getActivePackages: "/active",
    getPackageById: "/:id",
    deletePackageById: "/:id",
    togglePackageStatus: "/:id/status",
  },
  packageprice: {
    upsertPackagePrice: "/upsert",
    getAllPackagePrices: "/",
    getPackagePriceById: "/:id",
    deletePackagePriceById: "/:id",
    togglePackagePriceStatus: "/:id/status",
    getSubPackagesByPackageId: "/sub-packages/:package_id",
  },
  paymentreports: {
    getAllPayments: "/all",
    exportAllPayments: "/export-all",
    exportPaymentById: "/export/:paymentId",
    getPaymentById: "/:paymentId",
  },
  ride: {
    getAllRides: "/all",
    getRideById: "/:id",
    createRide: "/",
    updateRide: "/:id",
    getAvailableCarsAndPrices: "/available-cars/:package_id/:sub_package_id",
  },
  ridesreports: {
    getAllRides: "/all",
    exportAllRides: "/export-all",
    exportRideById: "/export/:rideId",
    getRideById: "/:rideId",
  },
  settings: {
    getSettings: "/",
    upsertSettings: "/",
  },
  "sub-package": {
    upsertSubPackage: "/upsert",
    getAllSubPackages: "/",
    getActiveSubPackages: "/active",
    getSubPackageById: "/:id",
    deleteSubPackageById: "/:id",
    toggleSubPackageStatus: "/:id/status",
    getSubPackagesByPackageId: "/by-package",
  },
  ticket: {
    getOpenTicketsHandler: "/",
    resolveTicketHandler: "/:id/resolve",
    createTicketHandler: "/create",
    updateTicketStatusHandler: "/:id/status",
  },
  vehicles: {
    getAllVehicles: "/",
    approveVehicle: "/:id/approve",
    rejectVehicle: "/:id/reject",
    verifyRc: "/:id/verify-rc",
    rejectRc: "/:id/reject-rc",
    verifyInsurance: "/:id/verify-insurance",
    rejectInsurance: "/:id/reject-insurance",
    getVehiclesByDriver: "/:driverId",
  },

  // for mobile
  "mob-driver": {
    verifyMobile: "/verify",
    blockDriverByIdentifier: "/status",
    updateProfileAndCarDetails: "/update-profile",
    verifdriverAccountDetailsyRc: "/account-details",
    deleteAccount: "/delete-account",
    checkStatus: "/check-status",
    getStatuses: "/get-notify-statuses",
    updateStatuses: "/update-notify-statuses",
    updateOneSignalId: "/update-onesignal-id",
    deleteOneSignalId: "/:id/delete-onesignal-id",
  },
  home: {
    getAllHomeData: "/dashboard",
    acceptRide: "/accept-ride",
    toggleDriverStatus: "/toggle-status",
    getRideDetails: "/ride/:ride_id",
    updateRideStatus: "/ride/:ride_id",
    getRidesByStatus: "/rides",
    upsertRide: "/upsert-ride",
    releaseDriverFromRide: "/release/:rideId",
    startRide: "/start-ride/:rideId",
    endRide: "/end-ride/:rideId",
    cancelRide: "/cancel-ride",
    getMyRides: "/my-rides",
    earningsHistory: "/earnings-history",
  },
  "mob-notifications": {
    getNotifications: "/notifications",
  },
  "mob-package": {
    getAllPackages: "/get-all-packages",
    getAllCarsBySubPackageId: "/get-all-cars/:sub_package_id",
    getSubPackagesByPackageId: "/get-sub-packages/:package_id",
    getPrice: "/get-price/:package_id/:sub_package_id/:car_id",
    getAllCars: "/get-all-cars",
  },
  "mob-ride": {
    upsertRide: "/upsert",
    getAllRides: "/get-all",
    getRideById: "/get-sub-packages/:rideId",
    getRidesByStatus: "/get-by-status/:status",
  },
  "mob-settings": {
    getAllSettings: "/get-all-settings",
  },
  "mob-ticket": {
    getAllSettings: "/ticket/create",
    getTicketsByUser: "/ticket/",
    ticketview: "/ticket/:id",
  },
  "mob-vehicle": {
    updateVehicle: "/update-vehicle",
    uploadDocuments: "/documents",
  },
  wallet: {
    addMoneyToWallet: "/add-money",
    verifyPayment: "/verify-payment",
    walletHistory: "/wallet-history",
    myWalletBalance: "/wallet-balance",
  },
};

module.exports = {
  endPoints,
};
